Used substituteinplace to fix different paths and point them at store, now it boots.
Still getting errors. Output below happens if preferences is opened.

onboard
john@atom

** (.onboard-wrapped:14143): WARNING **: Error retrieving accessibility bus address:
org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service
files
17:28:24.596 WARNING Onboard.Keyboard: Atspi typelib missing, at-spi key-synth unavailable
17:28:24.606 WARNING Onboard.AtspiStateTracker: Atspi typelib missing, auto-show unavailable
17:28:24.631 WARNING Config: mousetweaks GSettings schema not found, mousetweaks integration
disabled.

(onboard:14143): dconf-WARNING **: failed to commit changes to dconf:
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by
any .service files

(onboard:14143): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property
GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a
future version

(onboard:14143): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property
GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a
future version

(onboard:14143): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property
GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be
removed in a future version

(onboard:14143): dconf-WARNING **: failed to commit changes to dconf:
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by
any .service files
Traceback (most recent call last):
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/XInput.py",
line 393, in _on_device_event
    callback(ev)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/TouchInput.py",
line 436, in _on_device_event
    self._on_button_release_event(self, event)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/TouchInput.py",
line 592, in _on_button_release_event
    self._input_sequence_end(sequence)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/TouchInput.py",
line 740, in _input_sequence_end
    self.on_input_sequence_end(sequence)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/KeyboardWidget.py",
line 1180, in on_input_sequence_end
    self.key_up(sequence)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/KeyboardWidget.py",
line 1239, in key_up
    not sequence.cancel_key_action)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/Keyboard.py",
line 1148, in key_up
    self._do_key_up_action(key, view, button, event_type)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/Keyboard.py",
line 1294, in _do_key_up_action
    self._release_non_sticky_key(key, view, button, event_type)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/Keyboard.py",
line 1664, in _release_non_sticky_key
    self.send_key_up(key, view, button, event_type)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/Keyboard.py",
line 1376, in send_key_up
    self.send_key_release(key, view, button, event_type)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/Keyboard.py",
line 1626, in send_key_release
    controller.release(view, button, event_type)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/Keyboard.py",
line 2834, in release
    run_script("sokSettings")
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/lib/python3.5/site-packages/Onboard/utils.py",
line 214, in run_script
    a =__import__(script)
  File
"/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/share/onboard/scripts/sokSettings.py",
line 2
    export
PATH=/nix/store/76rgpkm1jqgqwz4bjnk8y37z29q82zgy-python3-3.5.3/bin:/nix/store/sppr7zxhbnq6hvmf8vvw7k7jsrafqnbm-onboard-1.4.1/bin:/nix/store/63spjx86svppz695s5yy7mh2h6lbbca1-gtk+3-3.22.8-dev/bin:/nix/store/k6bmqyh6yf8pzrhnfbzkqdrb3g0hb5gj-expat-2.2.0-dev/bin:/nix/store/pmp2ysvnrmcfzdjmaqnyhda96zkf2z6f-glib-2.50.3-dev/bin:/nix/store/8xm32qg4xi1l41zng4xv752492h6wmdp-cairo-1.14.8-dev/bin:/nix/store/dg3c94l36n3zmrpq9p9qyfi6407rhv5f-freetype-2.6.5-dev/bin:/nix/store/6fc4ak60p1mnilrjfcyz0sywwmpmf45w-bzip2-1.0.6.0.1-bin/bin:/nix/store/j8japwvk2qq8wf9yddibs4fnp99hskkw-libpng-apng-1.6.28-dev/bin:/nix/store/fsqw38ydj8wfj606rzkdcb3rrmpnhb4q-fontconfig-2.12.1-bin/bin:/nix/store/3hz3ll4ikznx3b6cd3myvrm5i79kyj8y-harfbuzz-1.4.2-dev/bin:/nix/store/pr6x655sz1n1sqjhch2i64h5l8i48xrm-graphite2-1.3.6/bin:/nix/store/7wc7qlqg7vsbav3vrjmkfbjbxpp9nnpr-pango-1.40.3-bin/bin:/nix/store/mrzs48prbr7aync14ns4l2j2s489sx50-gdk-pixbuf-2.36.5-dev/bin:/nix/store/sqxw6zlqy91y5nhl4smr5smixkqhdr1k-libjpeg-turbo-1.5.1-bin/bin:/nix/store/s2hmf51bprsxb20v3bfigs8a7zsw3hjl-xz-5.2.2-bin/bin:/nix/store/i14lfjn7cgfmghak3hqczmd90dymsbaj-libtiff-4.0.7-bin/bin:/nix/store/8iavg1dpbz7w9lqgv35q0a6hdkr0gpxi-jasper-2.0.12-bin/bin:/nix/store/pj75dhcgcnnv7ws860bs2zf23hzk2bjz-gdk-pixbuf-2.36.5/bin:/nix/store/qja3mjgiz9c7ld1ddffgc7b487mv1zmh-gobject-introspection-1.50.0-dev/bin:/nix/store/6l6kkkvbz9nxc7pi8m4wcq0z60bmp74a-wayland-1.12.0/bin:/nix/store/q5l53jgm2crfih93l56lcl8mxjywygs9-cups-2.1.4-dev/bin:/nix/store/3gi4zw66q73hdal18akrca30rf02zblq-cups-2.1.4/bin:/nix/store/bx1091kbmwff89gmmxy3za426ryxg0jm-gtk+3-3.22.8/bin:/nix/store/2byhribnzhiy7zhp838fc833xdhnl5l8-dconf-0.26.0/bin:/nix/store/iwm7yk3a40wn400wlqv0rx0zhc7rk756-libcanberra-0.30/bin:/nix/store/px7a1kq4prjzw17c9pppssdmibqqdm2p-systemd-232/bin:/nix/store/fi3mbd2ml4pbgzyasrlnp0wyy6qi48fh-bash-4.4-p5/bin:/nix/store/nqini3ad62zhsknqdpsjcgcm68d1n4gl-hunspell-1.3.3-bin/bin:/nix/store/q2djjbafrmarpv3iqc6scqnsxrdlqxvb-pkg-config-0.29/bin:/nix/store/0l73r9z7q5zjyvghnkd9wm8bihf9gg2p-intltool-0.51.0/bin:/nix/store/lkdr3z34n6n17g7xiaw8plyw7hv9idsl-gettext-0.19.8/bin:/nix/store/nsa311yg8h93wfaacjk16c96a98bs09f-perl-5.22.3/bin:/nix/store/4yn2vyzz1mwl9ry9l67y9bmyasjp7jrj-python3.5-setuptools-30.2.0/bin:/nix/store/087w6yxwq3skp2zppahq8dvfa2idckv7-librsvg-2.40.16/bin${PATH:+:}$PATH
              ^
SyntaxError: invalid syntax