Got much further, now getting missing gtk3.
/nix/store/d8r3vhys2bm3ylljlj1hvspjizsx8z7y-onboard-1.4.1/bin/onboard                        john@atom
Traceback (most recent call last):
  File "/nix/store/d8r3vhys2bm3ylljlj1hvspjizsx8z7y-onboard-1.4.1/bin/.onboard-wrapped", line 36, in <module>
    from Onboard.OnboardGtk import OnboardGtk as Onboard
  File "/nix/store/d8r3vhys2bm3ylljlj1hvspjizsx8z7y-onboard-1.4.1/lib/python3.5/site-packages/Onboard/OnboardGtk.py", line 35, in <module>
    require_gi_versions()
  File "/nix/store/d8r3vhys2bm3ylljlj1hvspjizsx8z7y-onboard-1.4.1/lib/python3.5/site-packages/Onboard/Version.py", line 24, in require_gi_versions
    gi.require_version('Gtk', '3.0')
  File "/nix/store/sgqhypg37ad4gvgsj5r9gvz1a680xzh3-python3.5-pygobject-3.22.0/lib/python3.5/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available